FROM runpod/pytorch:2.0.1-py3.10-cuda11.8.0-devel
WORKDIR /app
RUN git clone https://github.com/bmaltais/kohya_ss.git .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "-u", "handler.py"]
